server:
  port: 5005

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dinesh-3/cm-cloud-config
          clone-on-start: true